server:
   port: 8201
sprig:
   profile: dev
   application:
      name: microservicecloud-config-client
eureka:
   client:
     service-url:
        defaultZone: http://eureka-dev.com:7001/eureka/

---

server:
   port: 8202
sprig:
   profile: test
   application:
      name: microservicecloud-config-client
eureka:
   client:
     service-url:
        defaultZone: http://eureka-test.com:7001/eureka/
